### ISSUE TITLE
下载不了依赖的文件

### ISSUE THREAD

**Issue by xiaoguxg** [maptalks/site#5]
![image](https://cloud.githubusercontent.com/assets/8435230/21671192/a489bbce-d354-11e6-8439-ef7dd91acaf2.png)

**Comment by fuzhenn** [comment]
还没发布呢, 网站还没上线~

**Comment by xiaoguxg** [comment]
那我想引入maptalks.js还有maptalks.css现在应该怎样用啊

**Comment by fuzhenn** [comment]
要不加我qq吧, 21732416
